### ISSUE TITLE
mov-cli-anime is no more.

### ISSUE THREAD

**Issue by Fraei2** [JDALab/otaku-watcher#1]
If `mov-cli-anime` is still set in your config as the anime scraper, now it's time to switch to `otaku-watcher`.

```toml
[mov-cli.plugins]
anime = "otaku-watcher"
```
